DROP TABLE resources;
DROP SEQUENCE resources_seq;

DROP TABLE stages;
DROP SEQUENCE stages_seq;

DROP TABLE roles;
DROP SEQUENCE roles_seq;

DROP TABLE staff;
DROP SEQUENCE staff_seq;

DROP TABLE activities;
DROP SEQUENCE activities_seq;

DROP TABLE costs;
DROP SEQUENCE costs_seq;

DROP TABLE activity_resources;
DROP SEQUENCE activity_resources_seq;

DROP TABLE plans;
DROP SEQUENCE plans_seq;

DROP TABLE staff_roles;
DROP SEQUENCE staff_roles_seq;

DROP TABLE groups;
DROP SEQUENCE groups_seq;

DROP TABLE reviews;
DROP SEQUENCE reviews_seq;

DROP TABLE actions;
DROP SEQUENCE actions_seq;