---------------------------the following code is for droppping actions table--------------------------
DROP TABLE actions;
DROP SEQUENCE actions_seq;
PURGE RECYCLEBIN;
------------------------------------------------------------------------------------------------------

---------------------------the following code is for droppping reviews table--------------------------
DROP TABLE reviews;
DROP SEQUENCE reviews_seq;
PURGE RECYCLEBIN;
-------------------------------------------------------------------------------------------------------

---------------------------the following code is for droppping groups table--------------------------
DROP TABLE groups;
DROP SEQUENCE groups_seq;
PURGE RECYCLEBIN;
-------------------------------------------------------------------------------------------------------

---------------------------the following code is for droppping staff_roles table-----------------------
DROP TABLE staff_roles;
DROP SEQUENCE staff_roles_seq;
PURGE RECYCLEBIN;
----------------------------------------------------------------------------------------------------

---------------------------the following code is for droppping plans table--------------------------
DROP TABLE plans;
DROP SEQUENCE plans_seq;
PURGE RECYCLEBIN;
-------------------------------------------------------------------------------------------------------

---------------------------the following code is for droppping activity_resources table----------------
DROP TABLE activity_resources;
DROP SEQUENCE activity_resources_seq;
PURGE RECYCLEBIN;
-------------------------------------------------------------------------------------------------------

---------------------------the following code is for droppping costs table--------------------------
DROP TABLE costs;
DROP SEQUENCE costs_seq;
PURGE RECYCLEBIN;
-------------------------------------------------------------------------------------------------------

---------------------------the following code is for droppping activities table--------------------------
DROP TABLE activities;
DROP SEQUENCE activities_seq;
PURGE RECYCLEBIN;
-------------------------------------------------------------------------------------------------------

---------------------------the following code is for droppping staff table--------------------------
DROP TABLE staff;
DROP SEQUENCE staff_seq;
PURGE RECYCLEBIN;
-------------------------------------------------------------------------------------------------------

---------------------------the following code is for droppping roles table--------------------------
DROP TABLE roles;
DROP SEQUENCE roles_seq;
PURGE RECYCLEBIN;
-------------------------------------------------------------------------------------------------------

---------------------------the following code is for droppping stages table--------------------------
DROP TABLE stages;
DROP SEQUENCE stages_seq;
PURGE RECYCLEBIN;
-------------------------------------------------------------------------------------------------------

---------------------------the following code is for droppping resources table--------------------------
DROP TABLE resources;
DROP SEQUENCE resources_seq;
PURGE RECYCLEBIN;

-------------------------------------------------------------------------------------------------------